ThriftUni/.env.exaple
ThriftUni/.gitignore
ThriftUni/app.json
ThriftUni/app/(tabs)/index.tsx
ThriftUni/firebase.config.tsx
ThriftUni/package.json
ThriftUni/yarn.lock

- Added a .env file with Firebase configuration values prefixed by EXPO_PUBLIC_ as required by Expo.
- Implemented `firebase.config.tsx` to handle Firebase initialization and configuration.
- Added logic to dynamically use the correct Firebase app ID for iOS or Android based on the platform.
- Created a function to test and verify that all Firebase configuration values are properly loaded.
- Ensured Firebase initializes only if not previously initialized to prevent multiple instances.
This setup ensures proper integration of Firebase into the project and enables debugging of configuration values.
***When using an android device:***
```bash
Android Bundled 929ms node_modules\expo-router\entry.js (1207 modules)
(NOBRIDGE) LOG  Bridgeless mode is enabled
INFO 
JavaScript logs will be removed …
```

Add Firebase configuration and initialization with .env file

---

ThriftUni/app/(tabs)/_layout.tsx
ThriftUni/db-setup.tsx

Created collections for categories, listing, listing_categories.
Adapted the relational table diagram to our Firestore NoSQL database. More details will be provided on issue #134.

Created Firestore Collections for Categories

---

ThriftUni/app/(tabs)/my_listings.tsx

Added functionalities to the buttons on my Listing page, allowing users to press them to filter items from 'View All' to 'Sold' and providing a button to edit their listing in case they want to delete it.

Added functionality to the buttons on the My Listing page.

---

ThriftUni/app/(tabs)/WishlistPage.tsx

made WishlistPage ready for firebase once its done

---

ThriftUni/app/(tabs)/Profile.tsx
ThriftUni/package-lock.json
ThriftUni/yarn.lock

Profile page refactoring in which page components are separated and can be reused.

Profile Page Refactor

---

ThriftUni/app/(tabs)/_layout.tsx
ThriftUni/db-setup.tsx

Example code for listing_images documents, completing issue #135. Due to security restrictions, the listing_images collection and mock document was created via the Cloud Firestore console but document example can be found on db-setup.tsx

135 set up database table for listing images

---

ThriftUni/components/ListingDescription.tsx

Fixed imports and other changes that were not supposed to be made.

---

ThriftUni/app/(tabs)/main_page.tsx
ThriftUni/components/ListingDescription.tsx
ThriftUni/components/__tests__/ListingsTesting.tsx
ThriftUni/documentation/my_listings.md
ThriftUni/package-lock.json
ThriftUni/package.json

-  Debugged main page and ThriftUni so that it wouldn't crash the app if it's ran
-  Added complete button functionality for all buttons
-  Added working search bar
-  Made markdown for my_listings
- Added testing to main page and the pages it leads to, as wanted by the test plan made for Milestone 1
Closes #194 
Closes #192 
Closes #191 
Closes #132

Main page, my listings and lecture topic task completion

---

ThriftUni/categories-test.js

Closes #202
Delayed by local problems with Firebase CLI.

202 tdd unit tests for listing categories collection relations and behaviors

---

ThriftUni/listing_images-test.js

Created Unit Tests for listing_images behavior

---

ThriftUni/app/(tabs)/Profile.tsx
ThriftUni/app/(tabs)/WishlistPage.tsx
ThriftUni/app/(tabs)/interestsandsizes.tsx
ThriftUni/app/(tabs)/my_listings.tsx
ThriftUni/app/(tabs)/settings.tsx
ThriftUni/app/login/login.tsx
ThriftUni/components/ProtectedRoute.tsx
ThriftUni/firebase/firebase.config.tsx
ThriftUni/firebaseConfig.js

This PR implements a route protection system to ensure that only authenticated users can access sensitive screens within the application. The ProtectedRoute component has been added, leveraging Firebase's onAuthStateChanged to monitor user authentication status.
Protected Routes: Applied ProtectedRoute to restrict access to the following screens:
✅ WishlistPage.tsx
✅ Profile.tsx
✅ settings.tsx
✅ my_listings.tsx
✅ interestsandsizes.tsx
Redirection Logic: Unauthenticated users are automatically redirected to the login screen when attempting to access protected screens.
State Management: Ensures proper authentication state handling to avoid unauthorized access.
Navigation Edge Cases: Prevents back navigation to protected pages after logout to maintain security and consistency.

Protected routes

---

ThriftUni/app/(tabs)/my_listings.tsx
ThriftUni/components/__tests__/DisplayMyListing.test.tsx
ThriftUni/mock_backend/listingsData.json
ThriftUni/mock_backend/mockApi.ts
ThriftUni/package-lock.json
ThriftUni/package.json

Edit Modal Functionality
Added an Edit button to each listing (visible in editing mode).
Created a modal interface to update:
Title
Price
Description
Photos (add/remove via expo-image-picker)
Status (Sold, Pending, Active)
Updates are reflected immediately in the UI upon saving.
Mock Backend Integration
Developed a local mock backend using an in-memory JSON file and utility functions (mockApi.ts) to simulate:
getListings() – fetch all listings.
updateListing(id, data) – update a listing.
deleteListing(id) – remove a listing.
Eliminated the need for network/server setup, simplifying local development and testing.
Unit Testing with React Testing Library
Set up React Testing Library and Jest.
Mocked API calls to ensure deterministic test results.
Tests implemented:
Fetching Listings – …

Add Edit Modal, Mock Backend Integration, and Unit Tests for My Listing Page

---

ThriftUni/app/(tabs)/WishlistPage.tsx
ThriftUni/components/features/thrift_wishlist_.feature

this completes #270
made a feature folder for future BDD implementation
worked on creating the feature file for wishlist with the BDD implementation using gherkin

BDD for wishlist

---

ThriftUni/app/(auth)/signup.tsx

Add email verification to signup process

---

ThriftUni/components/__tests__/ThriftUniApp.test.tsx

Implemented test suites that check for mutations in main page design and fail if it catches any new changes.
closes #299

Mutation testing for main page

---

ThriftUni/app/(tabs)/WishlistPage.tsx
ThriftUni/components/__tests__/wishlist.steps.tsx

bdd wishlist testing

---

ThriftUni/backend/Fuzz-Tests-Script.js

Made script to fuzz API calls.
- Node.js
- Firebase SDK
- Custom JavaScript fuzzing script
- Console logs captured manually
- CSV report output via Python scripting
We performed fuzz testing on the following Firebase API endpoints:
- `getListings()`
- `getCurrentUserListings()`
- `getListingById(id)`
- `createListing(data)`
- `updateListing(id, data)`
- `deleteListing(id)`
- `getListingImages(listingId)`
Each function was tested using a variety of invalid, edge-case, and malicious payloads including:
- null
- undefined
- numbers, booleans, and strings
- functions, symbols, and dates
- XSS payloads and directory traversal attempts
| Input Type | Example Payload |
|------------|------------------|
| Null | `null` |
| Undefined | `undefined` |
| Number | `12345` |
| Boolean | `true`, `false` …

Add Api Fuzzing Script

---

ThriftUni/app/(tabs)/Profile.tsx
ThriftUni/app/(tabs)/privacypage.tsx
ThriftUni/components/ListingDescription.tsx
ThriftUni/yarn.lock

https://github.com/user-attachments/assets/138a8b0d-bb5f-4062-b3aa-8a863c84ad0e
close #344

Fix crash on Profile and PrivacyPage tabs

---

ThriftUni/.gitignore
ThriftUni/app/(auth)/__tests__/ForgotPass.test.js
ThriftUni/app/(auth)/__tests__/Signup.test.js
ThriftUni/app/(auth)/forgot.tsx
ThriftUni/app/(auth)/signup.tsx
ThriftUni/firebase/firebase.config.tsx
ThriftUni/firebase/forgot.tsx
ThriftUni/firebase/signup.tsx

Lecture topic tasks mutation testing for signup and forgot password feature

---

ThriftUni/app/(tabs)/my_listings.tsx
ThriftUni/backend/Api.ts

Also changed the API functions to reflect recent schema changes.
Closes #345 
* Created users document users/IKLvyFOhjgTfejmL01fA3Yfi4N73 via Sign Up page
* Created listings document listings/b6T6dofk3FLGkfXiFOmA
The listing displays in the My Listings page when the associated user is logged in.

Changed the current user reference to match the logged in user.
